### ISSUE TITLE
Option for base pair length in simNGS

### ISSUE THREAD

**Issue by azrasid** [mfumagalli/ngsSim#3]
Hi,
I need to simulate reads of different basepair length ( 100, 150, 250 etc)as output.
Is it possible to mention in the command of simNGS the basepair length I want.

I saw there is an option of —readlen ,  I wonder if it means the base pair length?

Please need your guidance.

**Comment by mfumagalli** [comment]
Hi, there is no concept of read length in ngsSim, all sites are simulated independently. You may wish to use a different simulator if you want to be explicit on the basepair length.

**Comment by azrasid** [comment]
Thanks for your response
